apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  selector:
    app: udagram-frontend
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  type: LoadBalancer
